---
  - name: Install Development Tools
    dnf:
      name: "@Development Tools"
      state: present

  - name: Install pip3
    package:
      name: python3-pip
      state: present

  - name: Install redhat-rpm-config
    dnf:
      name: redhat-rpm-config
      state: present

  - name: Install python3-devel
    dnf:
      name: python3-devel
      state: present

  - name: Install libselinux-python
    dnf:
      name: libselinux-python
      state: present

  - name: Install Buildbot
    pip:
      name: buildbot-worker
      executable: pip3
      state: present

  - name: Create buildbot user
    user:
      name: buildbot
      shell: /bin/bash

  - name: Create worker directory
    file:
      path: /home/buildbot/worker/
      state: directory
      owner: buildbot
      group: buildbot

  - name: Create info directory
    file:
      path: /home/buildbot/worker/info
      state: directory
      owner: buildbot
      group: buildbot

  - name: Set host info for buildbot
    template:
      src: host.j2
      dest: /home/buildbot/worker/info/host
      owner: buildbot
      group: buildbot

  - name: Set Admin info for buildbot
    template:
      src: admin.j2
      dest: /home/buildbot/worker/info/admin
      owner: buildbot
      group: buildbot

  - name: Create buildbot.tac
    template:
      src: buildbot.tac.j2
      dest: /home/buildbot/worker/buildbot.tac
      owner: buildbot
      group: buildbot

  - name: Create unit file for systemd
    template:
      src: buildbot-worker.service.j2
      dest: /usr/lib/systemd/system/buildbot-worker.service
      owner: root
      group: root

  - name: Start buildbot-worker
    service:
      name: buildbot-worker
      state: started
      enabled: yes
